### ISSUE TITLE
Use [<Literal>] on constants to erase them from the generated bundle

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Dzoukr/Feliz.Bulma#1]
Using module members with `[<Literal>]` for string constants makes them compile away as their value will be used inline in the generated bundle

**Comment by Dzoukr** [comment]
Sure. It is still very fresh, to-cleanup-and-refactor stuff, but I'll keep it here for tracking. Good point!

**Comment by Dzoukr** [comment]
Since now #2 is done, there are about one thousand lines of literals. I need to think how to extract them to proper `[<Literal>] by script, or I would blow my head of doing it manually. 😄

**Comment by Zaid-Ajaj** [comment]
Replace `let` by `let [<Literal>]` maybe?

**Comment by Dzoukr** [comment]
Uff, done. I had to write custom script, but it wasn't that hard.

**Comment by Zaid-Ajaj** [comment]
The generated classes are made literal but the consuming helpers are not. i.e.
```fs
module helpers =
    let isClearfix = PropertyBuilders.mkClass "is-clearfix"
    let isPulledLeft = PropertyBuilders.mkClass "is-pulled-left"
    let isPulledRight = PropertyBuilders.mkClass "is-pulled-right"

```
should be 
```fs
module helpers =
    let [<Literal>] isClearfix = PropertyBuilders.mkClass "is-clearfix"
    let [<Literal>] isPulledLeft = PropertyBuilders.mkClass "is-pulled-left"
    let [<Literal>] isPulledRight = PropertyBuilders.mkClass "is-pulled-right"
```
Otherwise Fable will generate unnecessary module exports. This way, they all still compile down to just strings

**Comment by Dzoukr** [comment]
Oh... This one... 🤦‍♂ I'll fix it, thanks!

**Comment by Dzoukr** [comment]
Oh, wait a moment. But they are `IReactProperty`, not `string` type.

**Comment by Zaid-Ajaj** [comment]
Ohh my bad. Then they should be a static class that has inline static members such that Fable ignores them altogether when compiled unless they are actually used 😀 

Before
```fs
[<RequireQualifiedAccess>]        
module tag = 
    let isNormal = PropertyBuilders.mkClass ClassLiterals.``is-normal``
    let isMedium = PropertyBuilders.mkClass ClassLiterals.``is-medium`` 
```
After
```fs
[<Fable.Core.Erase>]        
type tag = 
    static member inline isNormal = PropertyBuilders.mkClass ClassLiterals.``is-normal``
    static member inline isMedium = PropertyBuilders.mkClass ClassLiterals.``is-medium`` 
```

**Comment by Dzoukr** [comment]
Please can you review now (and close if ok for Fable) 🙏

**Comment by Zaid-Ajaj** [comment]
> Nested static classes not supported

They are not supported, but you still could...
```fs
[<RequireQualifiedAccess>]
module icon = 
  [<Fable.Core.Erase>]
  type fa = 
    static member inline solid n = PropertyBuilders.mkClass (sprintf "fas fa-%s" n)
    static member inline regular n = PropertyBuilders.mkClass (sprintf "far fa-%s" n)
    static member inline light n = PropertyBuilders.mkClass (sprintf "fal fa-%s" n)
    static member inline duotone n = PropertyBuilders.mkClass (sprintf "fad fa-%s" n)
    static member inline brands n = PropertyBuilders.mkClass (sprintf "fab fa-%s" n)
```
Though for font awesome I would recommend using the [zanaptak/TypedCssClasses](https://github.com/zanaptak/TypedCssClasses) typed provider to pull the icon names in design-time (or use the the type provider **in your build script** using [this](https://github.com/zanaptak/TypedCssClasses#getproperties) to generate static font awesome icons) 

The rest look good to me 👍

**Comment by Dzoukr** [comment]
Yeah... you are right. I can create helper for font awesome on project level and keep this one clean.
