### ISSUE TITLE
Undefined Reference in DateTimePicker

### ISSUE THREAD

**Issue by Slesa** [Dzoukr/Feliz.Bulma#118]
When trying to use the DateTimePicker extension, I get 
```
error FSHARP: The type 'IRefValue' is not defined
```
using V2.3 of DatePicker and 2.18 of Bulma. Am I missing something?

**Comment by Dzoukr** [comment]
Hmmm... that's strange. Anything related to React? @kstastny is quite an intensive user of DateTimePicker, so maybe he has some idea?

**Comment by kstastny** [comment]
I never saw this error before. @Slesa could you provide sample code to reproduce this issue?

**Comment by Slesa** [comment]
I copied the project into https://github.com/Slesa/FableEdit. By simply adding the nuget reference, I get the error.

**Comment by kstastny** [comment]
Try upgrading all your NuGet packages, e.g. Feliz in your project uses version 0.68.10 but Feliz.Bulma.DateTimePicker requires version 1.32 or newer.

**Comment by MangelMaxime** [comment]
@Slesa An error like that make me believe that you need to install `date-fns` NPM package.

It is required by Fable.DateFunctions which is a deps of Feliz.Bulma.DateTimePicker.

https://github.com/Zaid-Ajaj/Fable.DateFunctions

**Comment by Slesa** [comment]
Ah ok... I was not aware of the fact that I have to npm install packages on my own. I thought it would be some kind of magic done by Fable. Thanks a lot to all!

**Comment by MangelMaxime** [comment]
There [Femto](https://github.com/Zaid-Ajaj/Femto/) which can install the NPM dependencies for you. 

But it will only works if the different library authors added the required XML tags
