### ISSUE TITLE
Is the documentation correct regaring the version of Bulma (0.8.0) that is supported?

### ISSUE THREAD

**Issue by travis-leith** [Dzoukr/Feliz.Bulma#121]
I ask because I saw a completed PR (https://github.com/Dzoukr/Feliz.Bulma/pull/42) mentioning version 0.9.0

**Comment by MangelMaxime** [comment]
Hello @travis-leith,

it should indeed mentioned 0.9.0.

**Comment by Dzoukr** [comment]
Fixed, thanks for letting me know! I'll update docs when find time to fix failing pipeline (so weird error)
