### ISSUE TITLE
How do I add bulma-calendar to my style sheet

### ISSUE THREAD

**Issue by travis-leith** [Dzoukr/Feliz.Bulma#122]
I realise this is probably an obvious question for most people, but I know mostly F# stuff, not much web stuff.
Where is my style sheet? Do I just copy paste `@import "~bulma-calendar";` into it?

Links to docs: https://dzoukr.github.io/Feliz.Bulma/#/datetimepicker

**Comment by MangelMaxime** [comment]
In general such information can be found in the original NPM library.

Can be found here: https://bulma-calendar.onrender.com/

You put `@import "~bulma-calendar";` inside of your SASS/SCSS file where next to `@import "~bulma;" if you use SASS/SCSS.

**Comment by travis-leith** [comment]
@MangelMaxime, thanks for your help.
I am using the SAFE template. Looks like I need to add an entry to `index.html`. 
Adding `<link rel="stylesheet" href="~bulma-calendar/dist/css/bulma-calendar.min.css">` does not seem to work,
I note that the reference for bulma itself is fully qualified (`<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">`. So instead I have added `<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma-calendar@6.1.18/dist/css/bulma-calendar.min.css">` and it works.

Do you think it is worth providing this advice in the docs for Feliz.Bulma? If so, I'd be happy to submit a PR.

**Comment by MangelMaxime** [comment]
Personally, I don't think this information belongs to Feliz.Bulma. It is the responsibility of the NPM package to explains how to configure it.

There already is an "Installation tabs" on Feliz.Bulma documentation: https://dzoukr.github.io/Feliz.Bulma/#/datetimepicker

**Comment by travis-leith** [comment]
fair enough
