### ISSUE TITLE
Bulma.columns isCentered

### ISSUE THREAD

**Issue by sandeepc24** [Dzoukr/Feliz.Bulma#13]
Is there an example showing use of Bulma.columns.isCentered? I tried following and it is not working
```
    Bulma.columns [
        columns.isCentered
        Bulma.column [

```

**Comment by Dzoukr** [comment]
If you use custom IProperty (like `columns.isCentered`) and want to nest another components, you need to use `prop.children`:

```fsharp
Bulma.columns [
    columns.isCentered
    prop.children [
        Bulma.column [ ]
    ]
]
```

**Comment by sandeepc24** [comment]
Thanks.
