### ISSUE TITLE
Bulma Intellisense error: `Fable.React` does not contain `ReactElement`

### ISSUE THREAD

**Issue by mrakgr** [Dzoukr/Feliz.Bulma#133]
In Visual Studio, I get `The module/namespace 'Fable.React' from compilation unit 'Fable.React' did not contain the namespace, module or type 'ReactElement'` whenever I try to autocomplete Bulma. In Visual Studio Code, I get this at the top of the module.

[The project](https://github.com/mrakgr/SAFE-Stack---Vite-Template) compiles fine despite this using `dotnet run`.

What do I do about this? It might be due to me upgrading all the packages to the latest, but if so, I'd rather not resolve it by downgrading.

**Comment by MangelMaxime** [comment]
@mrakgr Hum, this is looks like a error related to he fact that you are using Fable.React 9 with a version of Feliz or Feliz.Bulma which doesn't support Fable.React 9.

You can either manually revert to Fable.React 8, Feliz 1, Feliz.Compiler 1, etc.

Or try to use Feliz 2, the pre release version of Feliz.Bulma 2. Note that if you use Feliz 2, you need to use Fable 4 prerelease.

**Comment by mrakgr** [comment]
Updating Fable to the prerelease is easy using `dotnet tool update fable --prerelease`, but I am having trouble figuring out how to do it for `Feliz.Bulma`. Any tips?

**Comment by mrakgr** [comment]
```
nuget Feliz prerelease
nuget Feliz.Bulma prerelease
```

I tried putting this in, but it doesn't seem like the version is changing.

**Comment by MangelMaxime** [comment]
> ```
> nuget Feliz prerelease
> nuget Feliz.Bulma prerelease
> ```
> 
> I tried putting this in, but it doesn't seem like the version is changing.

This is indeed the correct of doing it. Did you run `dotnet paket install` or `dotnet paket update`?

You can also check in your `paket.lock` which versions is used to be sure of what is happening.

**Comment by mrakgr** [comment]
`dotnet paket update`. I checked in the diff window, but the versions haven't changed from what you can see in the [lock file](https://github.com/mrakgr/SAFE-Stack---Vite-Template/blob/05e7c82cc0c154bc62a6256eca8408d76bd238b6/paket.lock#L132).

**Comment by MangelMaxime** [comment]
For Feliz, it is normal your version didn't change because this is already the latest version.

For Feliz.Bumla, I suspect that this is because the name of the version is not standard... You can pin the version your self manually. You will need to relax your Fsharp.Core restriction because Feliz.Bumla require Fsharp.Core v7.

```
nuget Fsharp.Core ~> 7
# ...
nuget Feliz.Bulma 3.0.0-pre-002
```

**Comment by mrakgr** [comment]
```
PS E:\Webdev\Fable\SAFE-Stack---Vite-Template> paket find-package-versions Feliz.Bulma
Paket version 7.2.0+bb14ab674b2748070a624f394cd6796e11aaffa8
3.0.0-pre-002
3.0.0-pre-001
2.19.0
2.18.0
```

I see, I could have just used this to check the versions. Yeah, it works now. Thank you.

**Comment by MangelMaxime** [comment]
Your welcome, I sent a PR trying to make Feliz.Bulma ready for stable version #134
