### ISSUE TITLE
Feliz.Bulma.Calendar

### ISSUE THREAD

**Issue by viktorvan** [Dzoukr/Feliz.Bulma#17]
I am getting a lot of warnings from webpack after adding Feliz.Bulma.Calendar. 

I tried cloning this repo (Feliz.bulma) and tried to build it (`dotnet fake build` which runs the "RunDocs" target) and I am getting the same warnings:

>WARNING in ../Feliz.Bulma.Calendar/node_modules/date-fns/locale/ar/index.d.ts 1:8
Module parse failed: Unexpected token (1:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> declare module 'date-fns/locale/ar' { }
|
 @ ../Feliz.Bulma.Calendar/node_modules/date-fns/locale sync ^\.\/.*$ ./ar/index.d.ts
 @ ../Feliz.Bulma.Calendar/node_modules/bulma-calendar/src/js/index.js
 @ ../Feliz.Bulma.Calendar/Calendar.js
 @ ../Feliz.Bulma.Calendar/Calendar.fs
 @ ./Views.Calendar.fs
 @ ./View.fs
 @ ./App.fs
 @ ./Docs.fsproj
 @ multi ./Docs.fsproj

Any clues on what is causing this?

**Comment by Dzoukr** [comment]
I think it is because of using `src` instead of `dist` in `calendar.js` file. I'll look at it.

**Comment by Dzoukr** [comment]
Fixed in `1.0.4`
