### ISSUE TITLE
Support for prop.classes

### ISSUE THREAD

**Issue by joshuacrew** [Dzoukr/Feliz.Bulma#18]
This may be the worng place for this, so feel free to close.

I was wondering if this library provides support for dealing with multiple classes?

```
Html.div [
    prop.classes [ "field"; "has-addons" ]
    prop.children [
      Html.div [
        prop.classes [ "control"; "is-expanded"]
        prop.children [
          Html.input [
            prop.classes [ "input"; "is-medium" ]
            prop.valueOrDefault state.NewTodo
            prop.onChange (SetNewTodo >> dispatch)
          ]
        ]
      ]
    ]
 ]
```

I am trying to convert this html block to use Feliz.Bulma instead, but have compilation issues when trying to write it in this way:

```
Bulma.field [
        field.hasAddons
        Bulma.control [
            control.isExpanded
            prop.children [
                Bulma.textInput [
                    input.isMedium
                    prop.valueOrDefault state.NewTodo
                    prop.onChange (SetNewTodo >> dispatch)
                ]
            ]       
        ]
    ]
```

I get this error:
This expression was expected to have type
    'IReactProperty'    
but here has type
    'Fable.React.ReactElement'

**Comment by Dzoukr** [comment]
Hi, I think the correct way of writing this is:

```fsharp
Bulma.field [
        field.hasAddons
        prop.children [
        // your Bulma.control here
        ]
    ]
```

**Comment by Dzoukr** [comment]
If it helped, please close the issue. 😉

**Comment by joshuacrew** [comment]
Thank you so much for the help - I'll close! 
I know it is not really my place, but I do think this is a really good idea -> #5
