### ISSUE TITLE
Missing column responsiveness classes 

### ISSUE THREAD

**Issue by MangelMaxime** [Dzoukr/Feliz.Bulma#19]
Column is missing responsive version of `is-1` ... `is-12`. 
[Bulma source code](https://github.com/jgthms/bulma/blob/master/sass/grid/columns.sass#L467-L504) to show that it's supported.

Same for `is-offset-1` ... `is-offset-12`

[Bulma source code](https://github.com/jgthms/bulma/blob/master/sass/grid/columns.sass#L423-L428) all the screen size have something similar to that part.

**Comment by Dzoukr** [comment]
Fixed in v2.9.0
