### ISSUE TITLE
Use module/component specific attributes from the same type

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Dzoukr/Feliz.Bulma#2]
I think it is better have attributes that are coming from the same component.

for example:
```fs
Bulma.input [
  input.isPrimary
  input.hasTextBlack
  input.isLarge
]

Bulma.button [
  button.isPrimary
  button.isLarge
  button.text "Click"
]
```
is better than having to look in different types for the component properties
```fs
Bulma.button [
  color.isPrimary
  size.isLarge
  prop.text "Click"
]
```

I know it requires a bit of duplication but the bundle size isn't impacted and it makes much much easier to look for properties on a per-component basis.

**Comment by Dzoukr** [comment]
I believe that's exactly what I am doing. E.g. `isLarge` can be found across many components, but I am adding them again for each type (actually not every class can be used everywhere so I am strictly following documentation here) instead of referencing one module. The only exception is colors (they can be used everywhere) and some text helper classes. Or am I missing something?

**Comment by Zaid-Ajaj** [comment]
> I believe that's exactly what I am doing.

Then ignore what I just said 😅 I was checking the `color` module and assumed this is how the rest of these module are written.

**Comment by Dzoukr** [comment]
No problem. At least someone cares! :smile: Thanks and please keep ideas coming. :pray:

**Comment by Zaid-Ajaj** [comment]
Of course, will sure do :smile:

**Comment by Dzoukr** [comment]
Hmmm. You made me think. 🤔 

Maybe we can have `color` module, but also re-check documentation for elements where colors can be set (buttons, dropdowns, etc...) and copy-paste to have `button.isPrimary` directly on `button` type available. I'll revisit it after all elements implemented.

**Comment by Dzoukr** [comment]
Yeah, I did it that way - now colors are on each type where allowed by docs.
