### ISSUE TITLE
Change the way how component color is defined and set

### ISSUE THREAD

**Issue by Dzoukr** [Dzoukr/Feliz.Bulma#22]
As agreed in #20, we should rethink how to work with colors. 
One way would be having `button.color color.isDanger`, or just have long list of possible colors and using it directly `color.isDanger` (which I like more right now). Should discuss further.

**Comment by Dzoukr** [comment]
Ok, let's focus on this now.

I think the approach for this should be:
- get rid of component color modifiers like 'button.isDanger'
- have just 'color.isDanger' everywhere

Then we would have unified way how to work with colors + less code in modifiers file

**Comment by MangelMaxime** [comment]
@Dzoukr 

I am not sure which API you are choosing but if it is `button.color.isDanger` and not `button.color color.isDanger`.

Then you should first try to design and extend `button.color.isDanger` API on a some portion or in Fable REPL. Personnally I didn't found a way to do it.

**Comment by Dzoukr** [comment]
I was thinking just about

```fsharp
Bulma.button [
    color.isDanger
]
```

**Comment by MangelMaxime** [comment]
I didn't think about this solution but that's good.

It's the same way of thinking as for `text` modifiers for example 👍

**Comment by Dzoukr** [comment]
I think we have this finished as well.
