### ISSUE TITLE
Special Text component 

### ISSUE THREAD

**Issue by MangelMaxime** [Dzoukr/Feliz.Bulma#28]
Probably related to #24 

In Fulma, I added a special `Text` component.

The idea was to have an easy way to customize the text using Fulma API.

[Fulma documentation](https://fulma.github.io/Fulma/#fulma/modifiers/typography)

I think that v1 of Feliz.Bulma expects you to use `Html.*` and custom `++` operator for that.

```fs
Html.p [
    text.isUppercase
    ++ text.isItalic
    ++ color.hasTextSuccess
    prop.text "Hello Feliz"
]
```

If we add:

- `Bulma.text.p`
- `Bulma.text.div`
- `Bulma.text.span`

Then we could just write:

```fs
Html.p [
    text.isUppercase
    text.isItalic
    color.hasTextSuccess
    prop.text "Hello Feliz"
]
```

Could we add this kind of component to Feliz.Bulma?

**Comment by Dzoukr** [comment]
Sure, why not. Maybe we can skip the `.text.` part and make it just `Bulma.p`, `Bulma.div` and `Bulma.span`?

**Comment by MangelMaxime** [comment]
It is indeed nicer from the usage/read perspective (less noise).

But, in term of discoverability, it is not that great. Perhaps, we will want to add `section` support in the future and people will not see it easily.

Also, if we do `Bulma.p` it makes it a special case in the API design. --> `Bulma.[class].[controlHtml]`

**Comment by MangelMaxime** [comment]
The idea with `Bulma.text.p` is:

1. I want to customize some text -> `Bulma.text`
2. I see the different HTML element I can use and pick one
3. Customize it using the properties and the property prefix is easy to identify because it's `text`

**Comment by Dzoukr** [comment]
Ok, that sounds good for me.

**Comment by Dzoukr** [comment]
Done
