### ISSUE TITLE
Title and subtitle do not set size modifiers in 2.0

### ISSUE THREAD

**Issue by bklop** [Dzoukr/Feliz.Bulma#37]
With Feliz Bulma 1.x, using Bulma.subtitle2 would result in an `<h2 class="subtitle is-2">`. After the upgrade to 2.0, Bulma.subtitle.h2 results in an `<h2 class="subtitle">`, i.e. without the size modifier.

**Comment by Dzoukr** [comment]
It's already fixed in #35 - will release new version soon

**Comment by Dzoukr** [comment]
`v2.1` released, sorry for troubles
