### ISSUE TITLE
Bulma.navbarBrand not defined?

### ISSUE THREAD

**Issue by salaerts** [Dzoukr/Feliz.Bulma#45]
Hi,

I'm probably doing something wrong but I'm getting an unexpected error which I don't understand.

I installed Feliz 1.13.0 and Feliz.Bulma 2.3.0 into a project generated by the SAFE template. The code I'm trying to write uses a navbar (parent html stripped out for brevity):

```
            Bulma.navbar [
                navbar.isPrimary
                prop.children [
                    Bulma.container [
                        container.isFluid
                        prop.children [
                            Bulma.navbarBrand [
                            ]
                        ]
                    ]
                ]
            ]
```
This code was taken from another example project on github.
At this point I get 2 exceptions when building the project:

- error FSHARP: The type 'navbar' does not define the field, constructor or member 'isPrimary'. (code 39)
- error FSHARP: The value, constructor, namespace or type 'navbarBrand' is not defined.

The Bulma wrapper should be working because I have other code that generates columns and some buttons which works just fine:

```
            Bulma.columns [
                Bulma.column [
                    column.is2
                    prop.children [
                        Bulma.button.a [
                            prop.onClick (fun _ -> dispatch Decrement)
                            prop.text "-"
                        ]
                    ]
                ]
                Bulma.column [
                    column.is2
                    prop.children [
                        Bulma.button.a [
                            prop.onClick (fun _ -> dispatch Increment)
                            prop.text "+"
                        ]
                    ]
                ]
            ]
```

Any idea what I'm doing wrong?

**Comment by MangelMaxime** [comment]
Hello, 

if I remember correctly you need to use `color.XXX` so it would give:

```fs
Bulma.navbar [ color.isPrimary ]
```

For  `navbarBrand` you need to specify which element will be generated: `Bulma.navbarBrand.div` for example.

PS: I write from head so perhaps the code need to be a bit adapted. You can also take a look at the source code it should be readable. For example, you here is the [`navbarBand`](https://github.com/Dzoukr/Feliz.Bulma/blob/master/src/Feliz.Bulma/Bulma.fs#L740-L748) definition

**Comment by salaerts** [comment]
You're right, works like a charm. Thanks a lot!
