### ISSUE TITLE
How to navbar?

### ISSUE THREAD

**Issue by pbryon** [Dzoukr/Feliz.Bulma#47]
Hi,

I'm relatively new at F#, so my apologies if the code in this repository is self-documenting to others.

I upgraded from `Feliz.Bulma` 1.14 to 2.3, and now my nav doesn't compile anymore.

Old code:

```fsharp
let private navbarStart dispatch user currentPage =
    Bulma.navbarStart [
        Bulma.navbarItemA [
            // content
        ]
        Bulma.navbarItemA [
            // content
        ]
    ]

let private navbarEnd =
    Bulma.navbarEnd [
        Bulma.navbarItemDiv [
            // content
        ]
    ]

let view dispatch user currentPage =
    Bulma.navbar [
        color.isPrimary
        prop.children [
            Bulma.container [
                container.isFluid
                prop.children [
                    Bulma.navbarBrand [
                        Bulma.navbarItemA [
                            // content
                        ]
                    ]
                    Bulma.navbarMenu [
                        navbarStart dispatch user currentPage
                        navbarEnd
                    ]
                ]
            ]
        ]
    ]
```

Everything works except the `Bulma.navbarStart`, `Bulma.navbarEnd` and `Bulma.navbarBrand`.

Could you give me any pointers on how to convert, or perhaps a basic template of what a nav should look like in the new version?

**Comment by Dzoukr** [comment]
Hello @pbryon, no problem.

In v2 we changed the way of creating elements to give you more control. One of the change also touched navbar. For example `navbarItemA` is now `navbarItem.a` or `navbarItem.div` and so on.

**Comment by pbryon** [comment]
Thanks, that did it! I didn't realise I had to apply the same logic to all element builders.
