### ISSUE TITLE
Error in documentation?

### ISSUE THREAD

**Issue by KingKnecht** [Dzoukr/Feliz.Bulma#52]
Hi,
if I copy paste the source from the documentation [Felix.Bulma](https://dzoukr.github.io/Feliz.Bulma/#/)
which is:
`Bulma.columns [ Bulma.column [ column.is2 // <-- note context helper here
                                                       prop.children [ Bulma.button "Click me" ] ] ] ])`

I get a
`The type 'Bulma' does not define the field, constructor or member 'button'. Maybe you want one of the following:
   buttons`
error.

I think it should be:

`Bulma.columns [ Bulma.column [ column.is2 // <-- note context helper here
                                                       prop.children [ Bulma.button`**.button**` "Click me" ] ] ] ])`

**Comment by MangelMaxime** [comment]
Hello, you are right it seems like we forget to update the documentation making the API changes.

Would you like to send a PR fixing the error?

**Comment by Dzoukr** [comment]
Thanks @KingKnecht for #54 !
