### ISSUE TITLE
Panel: Elements get ignored implicitly 

### ISSUE THREAD

**Issue by KingKnecht** [Dzoukr/Feliz.Bulma#57]
I'm trying to add a header to a panel like this:

```
Bulma.panel [

        Bulma.panelHeading [
          Html.text "Undo Redo Stack"
        ]

        for e in (state |> UndoList.toTimedList) ->
          match e with
          | Past (s, m) ->
              Bulma.panelBlock.a [
                Html.text (m.Description + " (past)")
              ]
          | Present (s, m) ->
              Bulma.panelBlock.div [
                Html.text (m.Description + " (present)")
              ]
          | Future (s, m) ->
              Bulma.panelBlock.a [
                Html.text (m.Description + " (future)")
              ]
      ]
```
this gives me a warning:

![image](https://user-images.githubusercontent.com/4339172/101262719-03bc3500-3741-11eb-946d-d0f93d6aa1c2.png)

`The result of this expression has type 'Fable.React.ReactElement' and is implicitly ignored. Consider using 'ignore' to discard this value explicitly, e.g. 'expr |> ignore', or 'let' to bind the result to a name, e.g. 'let result = expr'.`

And the header is not rendered:
![image](https://user-images.githubusercontent.com/4339172/101262676-c061c680-3740-11eb-8621-860568681090.png)

What am I doing wrong?

**Comment by Zaid-Ajaj** [comment]
@KingKnecht change
```fs
for e in (state |> UndoList.toTimedList) ->
```
into
```fs
for e in (state |> UndoList.toTimedList) do
```
