### ISSUE TITLE
Supporting span as select

### ISSUE THREAD

**Issue by brase** [Dzoukr/Feliz.Bulma#64]
Is it possible to support also spans as select? 
I am thinking of something like this:

```f#
Bulma.select.span [ ]

//and

Bulma.select.div [ ]
```

I could send you a PR but that will break things. What do you think?

**Comment by MangelMaxime** [comment]
Hello @brase, 

According to Bulma documentation seems to expect `select` classes to be hosted in a `div`. 

By changing `div` to `span` on the Bulma website I don't see a visual difference between any of them. I checked the Bulma source code and it doesn't have a rule for `span` in [select.sass](https://github.com/jgthms/bulma/blob/2cbef5868e3afbc54f8793c6785f6acd0205acb6/sass/form/select.sass)

Why do you need a span?

**Comment by brase** [comment]
I am using a template where the author used it this way. Thought it was valid in Bulma.

Got it. It is a really bad idea to change it this way. Next time I check the docs. I swear!

**Comment by MangelMaxime** [comment]
No problem :)

It is possible that we missed something in the implementation or that a new feature is not supported correctly. But indeed, keeping the customization feature to the minimum required make it is easier for the user.
