### ISSUE TITLE
How do I set tags in Feliz.Bulma.TagsInput?

### ISSUE THREAD

**Issue by SimonTC** [Dzoukr/Feliz.Bulma#73]
I am most likely missing something, but I cannot figure out how to set values on the `TagsInput` component.

I am using the TagsInput component in a form. By default, the list of tags is empty. When the form has been filled out and submitted, I would like the TagsInput component to become empty again. How do I do that? I cannot set the tags directly, and default values are only set when the page is initially loaded.

Here is the code I'm using to generate the TagsInput:
```
Bulma.field.div [
	prop.children[
		Bulma.label "Main ingredients"
		TagsInput.input[
			tagsInput.defaultValue model.MainIngredients
			tagsInput.onTagsChanged (fun tags -> SetMainIngredients tags |> dispatch)
			tagsInput.placeholder "e.g chicken, pasta"
			tagsInput.allowDuplicates false
			tagsInput.caseSensitive false
			tagsInput.tagProperties[
				tag.isRounded
				color.isPrimary
			]
		]
	]
]
```

**Comment by Dzoukr** [comment]
I am afraid that's the issue of uncontrolled input from React. I may rewrite component to behave like a controlled one.

**Comment by Dzoukr** [comment]
Ok, that was easier than expected. 😄 Fixed in next version. See bottom of https://dzoukr.github.io/Feliz.Bulma/#/tagsinput
