### ISSUE TITLE
Feliz.Bulma.Calendar get value 

### ISSUE THREAD

**Issue by Akash-Mair** [Dzoukr/Feliz.Bulma#81]
Hey Roman!

I couldn't find the right property to bind my calendar pickers value to my model's values so that if I change the dates in code or using another component theyre reflected in the input box of the calendar. Is that something you've mapped over?

Many thanks :)

**Comment by Dzoukr** [comment]
Hi @Akash-Mair, I am afraid it's not currently possible. Maybe it would be possible to force re-render based on model's value (using `prop.key` in wrapper div) but you'd need to try it.

**Comment by Akash-Mair** [comment]
Thanks for letting me know so quick!

**Comment by Dzoukr** [comment]
No problem! Sorry for not having a better response. 😄
