### ISSUE TITLE
Can we relax FSharp.Core requirements on this library?

### ISSUE THREAD

**Issue by MangelMaxime** [Dzoukr/Feliz.Bulma#90]
Hello,

It is currently requiring FSharp.Core 5.0 but I don't think it is using any feature from that version. Feliz is still on 4.7.2

It is possible to apply the "rules" to all the packages in the directory by adding a `Directory.Build.targets` like [this one](https://github.com/fable-compiler/fable-browser/blob/c3946446c13d6df6c6ed375ee6e79def93143348/src/Directory.Build.targets)

At least, it is how we did it for Fable projects

**Comment by Dzoukr** [comment]
Hi Maxime, sure! Feel free to send a PR. Just thinking... Could it be solved also on `paket.dependencies` level?
